spring:
    #    profiles:
    #        include: oauth
    h2:
        console:
            enabled: true
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: client-id
                        client-secret: client-secret
                        scope: profile,email
